@VersioningImplementationindotnetcoreWithDummyData_HostAddress = http://localhost:5126

GET {{VersioningImplementationindotnetcoreWithDummyData_HostAddress}}/weatherforecast/
Accept: application/json

###
